name: wattles
description: A lightweight ORM with no code generation.
version: 0.0.1-dev.1
repository: https://github.com/wolfenrain/wattles
issue_tracker: https://github.com/wolfenrain/wattles/issues
# homepage: https://wattl.es
# documentation: https://docs.wattl.es

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
